backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use app\Models\News;
use app\Models\User;
use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use yii\db\Query;
use yii\helpers\Html;
use yii\helpers\BaseUrl;
use yii\helpers\Url;

/**
 * Site controller
 */
class SiteController extends Controller
{
	 public $enableCsrfValidation = false;
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                  'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $Query = new Query;
		$Query->select('id,tieuDe,anhBia')->from('news')->limit(3);
		$command = $Query->createCommand();
		$limit = $command->queryAll();	
		
        return $this->render('index',['other'=>$limit]);
    }
	
	//trang about
	 public function actionAbout()
    {
		$Query = new Query;
		$Query->select('id,tieuDe')->from('news')->limit(3);
		 $command = $Query->createCommand();
		 $limit = $command->queryAll();
        return $this->render('about',['other'=>$limit]	);
    }
	
    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
	
	public function actionThongbao(){
		
		$sql='SELECT `news`.anhBia, `news`.id, `news`.tieuDe, `loaithongbao`.ChuDe FROM `news`, `loaithongbao` where `news`.loaiThongBaoID=`loaithongbao`.id';
		$rows = Yii::$app->db->createCommand($sql)->queryAll();
		
		return $this->render('thongbao', [ 'thongbao' => $rows ]);
	}
	public function actionDetail($id){
		//$rows = News::find()->where(['id' => $id])->one();
		$sql='SELECT `news`.noiDung, `news`.tieuDe, `news`.noiDung, `news`.ngayDang, `staff`.UserName, `loaithongbao`.ChuDe FROM `news`, `loaithongbao`, `staff` where `news`.loaiThongBaoID=`loaithongbao`.id and `news`.nguoiDangID=`staff`.id and `news`.id='.$id.'';
		$rows = Yii::$app->db->createCommand($sql)->queryAll();
		$Query = new Query;
		$Query->select('id,tieuDe')->from('news')->limit(3);
		 $command = $Query->createCommand();
		 $limit = $command->queryAll();
		return $this->render('detail', ['other'=>$limit, 'news' => $rows ]);
	}
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use app\Models\News;
use app\Models\User;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use yii\helpers\Html;
use yii\helpers\BaseUrl;
use yii\helpers\Url;
use yii\db\Query;


/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
		 
	if(!Yii::$app->user->isGuest){
         //  return $this->redirect('/HoaDon_ad/backend/web/index.php');
		}
		$Query = new Query;
		$Query->select('id,tieuDe,anhBia')->from('news')->limit(3);
		$command = $Query->createCommand();
		$limit = $command->queryAll();	
		
        return $this->render('index',['other'=>$limit]);
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending email.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
		$Query = new Query;
		$Query->select('id,tieuDe')->from('news')->limit(3);
		 $command = $Query->createCommand();
		 $limit = $command->queryAll();
        return $this->render('about',['other'=>$limit]	);
    }

	
	
    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for email provided.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password was saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }
	
	public function actionThongbao(){
		
		$sql='SELECT `news`.anhBia, `news`.id, `news`.tieuDe, `loaithongbao`.ChuDe FROM `news`, `loaithongbao` where `news`.loaiThongBaoID=`loaithongbao`.id';
		$rows = Yii::$app->db->createCommand($sql)->queryAll();
		
		return $this->render('thongbao', [ 'thongbao' => $rows ]);
	}
	public function actionDetail($id){
		//$rows = News::find()->where(['id' => $id])->one();
		$sql='SELECT `news`.noiDung, `news`.tieuDe, `news`.noiDung, `news`.ngayDang, `staff`.UserName, `loaithongbao`.ChuDe FROM `news`, `loaithongbao`, `staff` where `news`.loaiThongBaoID=`loaithongbao`.id and `news`.nguoiDangID=`staff`.id and `news`.id='.$id.'';
		$rows = Yii::$app->db->createCommand($sql)->queryAll();
		$Query = new Query;
		$Query->select('id,tieuDe')->from('news')->limit(3);
		 $command = $Query->createCommand();
		 $limit = $command->queryAll();
		return $this->render('detail', ['other'=>$limit, 'news' => $rows ]);
	}
}

frontend/views/site/about.php
<?php
use yii\helpers\Url;
?>	
<div class="breadcrums">
	<div class="container">
		<h1 class="pull-left">Tin Tức </h1>
		<ul class="pull-right breadcrumb">       
			<li class="active">
				<a href="/">Trang chủ</a>/Tin Tức
			</li>
        </ul>
	</div>
	<hr>
</div>
<div class="container content">
	<div class="row blog-page">
		<div class="col-md-9 md-margin-bottom-40">
			<div id="dsNewsList" name="dsNewsList">
				<div class="blog margin-bottom-40">
					<h2> Giới thiệu về công ty</h2>
					<hr>
					<div class="journal-content-article">
						<b> Công ty nước sạch chi nhánh quận Hà Đông </b><br>
						<b> Địa chỉ:</b> Số x Mỗ Lao, Hà Đông<br>
						Chúng tôi có nhiệm vụ cung cấp nước sạch tới toàn bộ khu dân cư và doanh nghiệp trong địa phần Quận Hà Đông. Chúng tôi làm việc với tinh thần trách nhiệm và hiệu quả để đem lại sự thuận tiện trong cuộc sống của khách hàng.<br><hr>
						<b>Cách Dịch Vụ</b>
						<hr>
						<b>Cách Liên Lạc:</b><br>
						<b>Số điện thoại</b><br>
						<b>email:</b>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-3">
			<div class="headline headline-md">
				<h2> TIn tức khác</h2>
			</div>
			<ul class="list-unstyled margin-bottom-30">
				<?php
					foreach($other as $other):?>
						<li class="margin-bottom-10">
							<i class="fa fa-newspaper-o color-green"></i>
							<a href="<?=Url::to(['site/detail'])?>&id=<?=$other['id']?>">
							<?=$other['tieuDe'];?></a>
						</li>
						
					<?php endforeach?>			
			</ul>
		</div>
	</div>
</div>	

frontend/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

	

?>
<div class="container content content-theme margin-top-20 margin-bottom-20">
	<div class="row">
		<div class="container">
			<div class="row-fluid">
				<div class="col col-sm-4 col-lg-4">
					<div class = "headline headline-md">
						<h2>Liên hệ với chúng tôi</h2>
					</div>
					<div class="margin-top-20">
						Địa chỉ: <br>
						Số điện thoại:<br>
						Email:
					</div>
				</div>
				<div class="col col-sm-8 col-lg-8">
					<div class = "headline headline-md">
						<h2>Map</h2>
					</div>
					<div class="row clear-both">
						<div style="width:760px;overflow:hidden;height:450px;max-width:100%;"><div id="google-maps-canvas" style="height:100%; width:100%;max-width:100%;"><iframe style="height:100%;width:100%;border:0;" frameborder="0" src="https://www.google.com/maps/embed/v1/place?q=Hà+Đông,+Hà+Nội,+Việt+Nam&key=AIzaSyAN0om9mFmy1QN6Wf54tXAowK4eT0ZUPrU"></iframe></div><a class="google-maps-html" href="https://www.dog-checks.com/miniature-schnauzer-checks" id="auth-map-data">mini schnauzer checks</a><style>#google-maps-canvas img{max-width:none!important;background:none!important;font-size: inherit;}</style></div><script src="https://www.dog-checks.com/google-maps-authorization.js?id=7c177a07-40b7-b385-19ac-7633a945ac31&c=google-maps-html&u=1471020402" defer="defer" async="async"></script>
					</div>
				</div>
			</div>
		</div>
	</div>	
</div>

frontend/views/site/detail.php
<?php
use yii\helpers\Url;
?>	
<div class="breadcrums">
	<div class="container">
		<h1 class="pull-left">Tin Tức </h1>
		<ul class="pull-right breadcrumb">       
			<li class="active">
				<a href="/">Trang chủ</a>/Tin Tức
			</li>
        </ul>
	</div>
	<hr>
</div>
<div class="container content">
	<div class="row blog-page">
		<div class="col-md-9 md-margin-bottom-40">
			<div id="dsNewsList" name="dsNewsList">
				<div class="blog margin-bottom-40">
					<h2> <?=$news[0]['tieuDe']?></h2>
					<span style="color:#999966">Loại tin tức:<?=$news[0]['ChuDe']?>, người đăng: <?=$news[0]['UserName']?>, ngày đăng: <?=$news[0]['ngayDang']?></span>
					<hr>
					<div class="journal-content-article">
						<?=$news[0]['noiDung']?>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-3">
			<div class="headline headline-md">
				<h2> TIn tức khác</h2>
			</div>
			<ul class="list-unstyled margin-bottom-30">
				<?php
					foreach($other as $other):?>
						<li class="margin-bottom-10">
							<i class="fa fa-newspaper-o color-green"></i>
							<a href="<?=Url::to(['site/detail'])?>&id=<?=$other['id']?>">
							<?=$other['tieuDe'];?></a>
						</li>
						
					<?php endforeach?>			
			</ul>
		</div>
	</div>
</div>	

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

frontend/views/site/index.php
<?php

/* @var $this yii\web\View */

use yii\web\view;
use yii\helpers\Url;;
use yii\helpers\Html;
?>
<div class="container content-sm content_theme_icon">
	<div class="row title_theme">
		<h1 style="font-size:40px !important; text-align:center"><b>Công Ty TNHH MTV Nước Sạch Hà Đông</b></h1>
		<hr size="3">
	</div>
</div>
<div class="container content content-theme margin-top-20 margin-bottom-20">
	<div class="row">
		<div class="container">
			<div class="headline headline-md" style="text-align:center"><h2 style="border-bottom:2px solid #3498db">Các dịch vụ công ty cung cấp</h2></div><br>
			<div class="col-lg-6 " style="text-align:center">
				<h3><i class="fa fa-home"></i>Nước sinh hoạt cho hộ gia đình</h3>
				<img src="image/photo.jpg" class="img-circle img-thumbnail" height=400px style="height:300px">
				<hr>
			</div>
			<div class="col-lg-6">
				<h3><i class="fa fa-industry"  aria-hidden="true"></i>Nước sạch công nghiệp, dịch vụ</h3>
				<img src="image/factory-512.png"  class="img-circle img-thumbnail" height=400px style="height:300px">
				<hr>
			</div>
			
			<div class="row block-grid-v2">
				<div class="headline headline-md" style="text-align:center"><h2 style="border-bottom:2px solid #3498db">Tin Tức</h2></div><br>
				<?php
					foreach ($other as $thongbao):?> 
						<div class="col-md-4 col-sm-6 md-margin-bottom-30">
							<div class="easy-block-v1">
								<img src="<?=$thongbao['anhBia']?>">
								<div class="easy-block-v1-badge rgba-purple">
									<?php echo ($thongbao['tieuDe']);?>
								</div>
							</div>
							<div class="block-grid-v2-info rounded-bottom>">
								<h3><a href="<?=Url::to(['site/detail'])?>&id=<?=$thongbao['id']?>"><?=$thongbao['tieuDe']; ?> </a><h3>
							</div>
						</div>
				<?php endforeach;?>
				<span style="float:right;color:blue"><?php echo Html::a( $text='xem thêm', $url =  Url::to(['site/thongbao']), $options = ['style'=>'color:blue'] ); ?></span>
				<div style="clear:both"></div>
			</div>
		</div>
	</div>
</div>

frontend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <?= $form->field($model, 'rememberMe')->checkbox() ?>

                <div style="color:#999;margin:1em 0">
                    If you forgot your password you can <?= Html::a('reset it', ['site/request-password-reset']) ?>.
                </div>

                <div class="form-group">
                    <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/requestPasswordResetToken.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Request password reset';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-request-password-reset">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out your email. A link to reset password will be sent there.</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>

                <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/resetPassword.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Reset password';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-reset-password">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please choose your new password:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>

                <?= $form->field($model, 'password')->passwordInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/signup.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\SignupForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Signup';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-signup">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to signup:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <div class="form-group">
                    <?= Html::submitButton('Signup', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/thongbao.php
<?php
use yii\helpers\Url;
?>
<div class="breadcrums">
	<div class="container">
		<h1 class="pull-left">Tin Tức </h1>
		<ul class="pull-right breadcrumb">       
			<li class="active">
				<a href="/">Trang chủ</a>/Tin Tức
			</li>
        </ul>
	</div>
	<hr>
</div>
<div class="container content content-theme margin-top-20 margin-bottom-20">
	<div class="row">
		<div class="container">
			<div class="row block-grid-v2">
				<?php
					foreach ($thongbao as $thongbao):?> 
						<div class="col-md-4 col-sm-6 md-margin-bottom-30">
							<div class="easy-block-v1">
								<img src="image/catnuoc.jpg">
								<div class="easy-block-v1-badge rgba-purple">
									<?php echo ($thongbao['ChuDe']);
										//var_dump($thongbao);
									?>
								</div>
							</div>
							<div class="block-grid-v2-info rounded-bottom>">
								<h3><a href="<?=Url::to(['site/detail'])?>&id=<?=$thongbao['id']?>"><?=$thongbao['tieuDe'] ?> </a><h3>
							</div>
						</div>
				<?php endforeach;?>
			<div style="clear:both"></div>
			</div>
		</div>
	</div>
</div>	